version: '3'
services:
  postgres:
    image: postgres:11.5-alpine
    container_name: postgres_abalon
    hostname: postgres
    environment:
      - PGDATABASE=abalon
      - POSTGRES_DB=abalon
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    volumes:
      - $HOME/docker/volumes/postgres_abalon:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 10s
      timeout: 5s
      retries: 5
  server:
    build: .
    container_name: server_abalon
    ports:
      - 12345:12345
    links:
      - postgres:postgres
    depends_on:
      - postgres